print("PPPPPP  Y     Y  TTTTTT  H     H  OOOOOO  N   N")
print("P    P   Y   Y     T     H     H  O    O  NN  N")
print("PPPPPP    Y Y      T     HHHHHHH  O    O  N N N")
print("P          Y       T     H     H  O    O  N  NN")
print("P          Y       T     H     H  OOOOOO  N   N")
