l=input()
c=l
c=c.isupper()
if(c==True):
    if(l=="A"):
        print("mayuscula")
        print("vocal")
    elif(l=="E"):
        print("mayuscula")
        print("vocal")
    elif(l=="I"):
        print("mayuscula")
        print("vocal")
    elif(l=="O"):
        print("mayuscula")
        print("vocal")
    elif(l=="U"):
        print("mayuscula")
        print("vocal")
    else:
        print("minuscula")
        print("consonante")
else:
    if(l=="a"):
        print("minuscula")
        print("vocal")
    elif(l=="e"):
        print("minuscula")
        print("vocal")
    elif(l=="i"):
        print("minuscula")
        print("vocal")
    elif(l=="o"):
        print("minuscula")
        print("vocal")
    elif(l=="u"):
        print("minuscula")
        print("vocal")
    else:
        print("minuscula")
        print("consonante")
